# Generated by Django 6.0 on 2026-01-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_email_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='api_emailot_email_9a9995_idx',
            old_name='api_emailo_email_ea1e1e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='api_emailot_email_35d737_idx',
            old_name='api_emailo_email_6f6b74_idx',
        ),
    ]
