# Generated by Django 6.0 on 2025-12-25 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='paid_end',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='paid_start',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid')], default='FREE', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
