# Generated by Django 6.0 on 2025-12-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersubscription_paid_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
